apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterprise-security-stack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise-security-stack.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.type "NodePort") .Values.nodePort.enabled }}
    nodePort: {{ .Values.nodePort.apiPort }}
    {{- end }}
  selector:
    {{- include "enterprise-security-stack.selectorLabels" . | nindent 4 }}
